proto_library(
    name = "usertoken_proto",
    srcs = [
        "proto/external/auth/rights.proto",
        "proto/external/auth/usertokens.proto",
    ],
    "//visibility:public"
    deps = ["@com_google_protobuf//:timestamp_proto"],
)

