// Copyright 2020 Working Group Two AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: wgtwo/calling/v0/calling.proto

package v0

import (
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	v0 "github.com/working-group-two/wgtwoapis/wgtwo/callforward/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sdp_Type int32

const (
	Sdp_OFFER  Sdp_Type = 0
	Sdp_ANSWER Sdp_Type = 1
)

// Enum value maps for Sdp_Type.
var (
	Sdp_Type_name = map[int32]string{
		0: "OFFER",
		1: "ANSWER",
	}
	Sdp_Type_value = map[string]int32{
		"OFFER":  0,
		"ANSWER": 1,
	}
)

func (x Sdp_Type) Enum() *Sdp_Type {
	p := new(Sdp_Type)
	*p = x
	return p
}

func (x Sdp_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sdp_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_wgtwo_calling_v0_calling_proto_enumTypes[0].Descriptor()
}

func (Sdp_Type) Type() protoreflect.EnumType {
	return &file_wgtwo_calling_v0_calling_proto_enumTypes[0]
}

func (x Sdp_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sdp_Type.Descriptor instead.
func (Sdp_Type) EnumDescriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{8, 0}
}

type Info_Message int32

const (
	Info_UNSPECIFIED Info_Message = 0
	Info_INITIATED   Info_Message = 1
	Info_RINGING     Info_Message = 2
	Info_ONGOING     Info_Message = 3
	Info_HANGUP_BUSY Info_Message = 4
	Info_HANGUP      Info_Message = 5
)

// Enum value maps for Info_Message.
var (
	Info_Message_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INITIATED",
		2: "RINGING",
		3: "ONGOING",
		4: "HANGUP_BUSY",
		5: "HANGUP",
	}
	Info_Message_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INITIATED":   1,
		"RINGING":     2,
		"ONGOING":     3,
		"HANGUP_BUSY": 4,
		"HANGUP":      5,
	}
)

func (x Info_Message) Enum() *Info_Message {
	p := new(Info_Message)
	*p = x
	return p
}

func (x Info_Message) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Info_Message) Descriptor() protoreflect.EnumDescriptor {
	return file_wgtwo_calling_v0_calling_proto_enumTypes[1].Descriptor()
}

func (Info_Message) Type() protoreflect.EnumType {
	return &file_wgtwo_calling_v0_calling_proto_enumTypes[1]
}

func (x Info_Message) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Info_Message.Descriptor instead.
func (Info_Message) EnumDescriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{10, 0}
}

type SendDtmfRequest_Dtmf int32

const (
	SendDtmfRequest_ZERO  SendDtmfRequest_Dtmf = 0
	SendDtmfRequest_ONE   SendDtmfRequest_Dtmf = 1
	SendDtmfRequest_TWO   SendDtmfRequest_Dtmf = 2
	SendDtmfRequest_THREE SendDtmfRequest_Dtmf = 3
	SendDtmfRequest_FOUR  SendDtmfRequest_Dtmf = 4
	SendDtmfRequest_FIVE  SendDtmfRequest_Dtmf = 5
	SendDtmfRequest_SIX   SendDtmfRequest_Dtmf = 6
	SendDtmfRequest_SEVEN SendDtmfRequest_Dtmf = 7
	SendDtmfRequest_EIGHT SendDtmfRequest_Dtmf = 8
	SendDtmfRequest_NINE  SendDtmfRequest_Dtmf = 9
	SendDtmfRequest_STAR  SendDtmfRequest_Dtmf = 10
	SendDtmfRequest_HASH  SendDtmfRequest_Dtmf = 11
)

// Enum value maps for SendDtmfRequest_Dtmf.
var (
	SendDtmfRequest_Dtmf_name = map[int32]string{
		0:  "ZERO",
		1:  "ONE",
		2:  "TWO",
		3:  "THREE",
		4:  "FOUR",
		5:  "FIVE",
		6:  "SIX",
		7:  "SEVEN",
		8:  "EIGHT",
		9:  "NINE",
		10: "STAR",
		11: "HASH",
	}
	SendDtmfRequest_Dtmf_value = map[string]int32{
		"ZERO":  0,
		"ONE":   1,
		"TWO":   2,
		"THREE": 3,
		"FOUR":  4,
		"FIVE":  5,
		"SIX":   6,
		"SEVEN": 7,
		"EIGHT": 8,
		"NINE":  9,
		"STAR":  10,
		"HASH":  11,
	}
)

func (x SendDtmfRequest_Dtmf) Enum() *SendDtmfRequest_Dtmf {
	p := new(SendDtmfRequest_Dtmf)
	*p = x
	return p
}

func (x SendDtmfRequest_Dtmf) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendDtmfRequest_Dtmf) Descriptor() protoreflect.EnumDescriptor {
	return file_wgtwo_calling_v0_calling_proto_enumTypes[2].Descriptor()
}

func (SendDtmfRequest_Dtmf) Type() protoreflect.EnumType {
	return &file_wgtwo_calling_v0_calling_proto_enumTypes[2]
}

func (x SendDtmfRequest_Dtmf) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendDtmfRequest_Dtmf.Descriptor instead.
func (SendDtmfRequest_Dtmf) EnumDescriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{20, 0}
}

type GetTurnServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId      string          `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	PhoneNumber *v0.PhoneNumber `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *GetTurnServersRequest) Reset() {
	*x = GetTurnServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTurnServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnServersRequest) ProtoMessage() {}

func (x *GetTurnServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnServersRequest.ProtoReflect.Descriptor instead.
func (*GetTurnServersRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{0}
}

func (x *GetTurnServersRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetTurnServersRequest) GetPhoneNumber() *v0.PhoneNumber {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

type GetTurnServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TurnServer []*TurnServer `protobuf:"bytes,1,rep,name=turn_server,json=turnServer,proto3" json:"turn_server,omitempty"`
}

func (x *GetTurnServersResponse) Reset() {
	*x = GetTurnServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTurnServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnServersResponse) ProtoMessage() {}

func (x *GetTurnServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnServersResponse.ProtoReflect.Descriptor instead.
func (*GetTurnServersResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{1}
}

func (x *GetTurnServersResponse) GetTurnServer() []*TurnServer {
	if x != nil {
		return x.TurnServer
	}
	return nil
}

type TurnServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Credential string `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *TurnServer) Reset() {
	*x = TurnServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TurnServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnServer) ProtoMessage() {}

func (x *TurnServer) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnServer.ProtoReflect.Descriptor instead.
func (*TurnServer) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{2}
}

func (x *TurnServer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TurnServer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TurnServer) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type StartCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId     string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	TerminalId string `protobuf:"bytes,2,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	// Types that are assignable to Message:
	//	*StartCallRequest_Init
	//	*StartCallRequest_Update
	Message isStartCallRequest_Message `protobuf_oneof:"message"`
}

func (x *StartCallRequest) Reset() {
	*x = StartCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallRequest) ProtoMessage() {}

func (x *StartCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallRequest.ProtoReflect.Descriptor instead.
func (*StartCallRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{3}
}

func (x *StartCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *StartCallRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (m *StartCallRequest) GetMessage() isStartCallRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *StartCallRequest) GetInit() *StartCallRequestInit {
	if x, ok := x.GetMessage().(*StartCallRequest_Init); ok {
		return x.Init
	}
	return nil
}

func (x *StartCallRequest) GetUpdate() *StartCallRequestUpdate {
	if x, ok := x.GetMessage().(*StartCallRequest_Update); ok {
		return x.Update
	}
	return nil
}

type isStartCallRequest_Message interface {
	isStartCallRequest_Message()
}

type StartCallRequest_Init struct {
	Init *StartCallRequestInit `protobuf:"bytes,3,opt,name=init,proto3,oneof"`
}

type StartCallRequest_Update struct {
	Update *StartCallRequestUpdate `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

func (*StartCallRequest_Init) isStartCallRequest_Message() {}

func (*StartCallRequest_Update) isStartCallRequest_Message() {}

type StartCallRequestInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromNumber *v0.PhoneNumber `protobuf:"bytes,1,opt,name=from_number,json=fromNumber,proto3" json:"from_number,omitempty"`
	ToNumber   *v0.PhoneNumber `protobuf:"bytes,2,opt,name=to_number,json=toNumber,proto3" json:"to_number,omitempty"`
	Sdp        *Sdp            `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *StartCallRequestInit) Reset() {
	*x = StartCallRequestInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCallRequestInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallRequestInit) ProtoMessage() {}

func (x *StartCallRequestInit) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallRequestInit.ProtoReflect.Descriptor instead.
func (*StartCallRequestInit) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{4}
}

func (x *StartCallRequestInit) GetFromNumber() *v0.PhoneNumber {
	if x != nil {
		return x.FromNumber
	}
	return nil
}

func (x *StartCallRequestInit) GetToNumber() *v0.PhoneNumber {
	if x != nil {
		return x.ToNumber
	}
	return nil
}

func (x *StartCallRequestInit) GetSdp() *Sdp {
	if x != nil {
		return x.Sdp
	}
	return nil
}

type StartCallRequestUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber *v0.PhoneNumber `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Sdp         *Sdp            `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *StartCallRequestUpdate) Reset() {
	*x = StartCallRequestUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCallRequestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallRequestUpdate) ProtoMessage() {}

func (x *StartCallRequestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallRequestUpdate.ProtoReflect.Descriptor instead.
func (*StartCallRequestUpdate) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{5}
}

func (x *StartCallRequestUpdate) GetPhoneNumber() *v0.PhoneNumber {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *StartCallRequestUpdate) GetSdp() *Sdp {
	if x != nil {
		return x.Sdp
	}
	return nil
}

type StartCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are assignable to Type:
	//	*StartCallResponse_KeepAlive
	//	*StartCallResponse_Sdp
	//	*StartCallResponse_Error
	//	*StartCallResponse_Info
	Type isStartCallResponse_Type `protobuf_oneof:"type"`
}

func (x *StartCallResponse) Reset() {
	*x = StartCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallResponse) ProtoMessage() {}

func (x *StartCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallResponse.ProtoReflect.Descriptor instead.
func (*StartCallResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{6}
}

func (x *StartCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (m *StartCallResponse) GetType() isStartCallResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *StartCallResponse) GetKeepAlive() *KeepAlive {
	if x, ok := x.GetType().(*StartCallResponse_KeepAlive); ok {
		return x.KeepAlive
	}
	return nil
}

func (x *StartCallResponse) GetSdp() *Sdp {
	if x, ok := x.GetType().(*StartCallResponse_Sdp); ok {
		return x.Sdp
	}
	return nil
}

func (x *StartCallResponse) GetError() *Error {
	if x, ok := x.GetType().(*StartCallResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *StartCallResponse) GetInfo() *Info {
	if x, ok := x.GetType().(*StartCallResponse_Info); ok {
		return x.Info
	}
	return nil
}

type isStartCallResponse_Type interface {
	isStartCallResponse_Type()
}

type StartCallResponse_KeepAlive struct {
	KeepAlive *KeepAlive `protobuf:"bytes,2,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type StartCallResponse_Sdp struct {
	Sdp *Sdp `protobuf:"bytes,3,opt,name=sdp,proto3,oneof"`
}

type StartCallResponse_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type StartCallResponse_Info struct {
	Info *Info `protobuf:"bytes,5,opt,name=info,proto3,oneof"`
}

func (*StartCallResponse_KeepAlive) isStartCallResponse_Type() {}

func (*StartCallResponse_Sdp) isStartCallResponse_Type() {}

func (*StartCallResponse_Error) isStartCallResponse_Type() {}

func (*StartCallResponse_Info) isStartCallResponse_Type() {}

type KeepAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{7}
}

func (x *KeepAlive) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Sdp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdp       string               `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Ufrag     string               `protobuf:"bytes,2,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      Sdp_Type             `protobuf:"varint,4,opt,name=type,proto3,enum=wgtwo.calling.v0.Sdp_Type" json:"type,omitempty"`
}

func (x *Sdp) Reset() {
	*x = Sdp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sdp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sdp) ProtoMessage() {}

func (x *Sdp) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sdp.ProtoReflect.Descriptor instead.
func (*Sdp) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{8}
}

func (x *Sdp) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *Sdp) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

func (x *Sdp) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Sdp) GetType() Sdp_Type {
	if x != nil {
		return x.Type
	}
	return Sdp_OFFER
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode    int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Error) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message     Info_Message `protobuf:"varint,1,opt,name=message,proto3,enum=wgtwo.calling.v0.Info_Message" json:"message,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{10}
}

func (x *Info) GetMessage() Info_Message {
	if x != nil {
		return x.Message
	}
	return Info_UNSPECIFIED
}

func (x *Info) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransferCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId      string          `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	PhoneNumber *v0.PhoneNumber `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Sdp         string          `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *TransferCallRequest) Reset() {
	*x = TransferCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCallRequest) ProtoMessage() {}

func (x *TransferCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCallRequest.ProtoReflect.Descriptor instead.
func (*TransferCallRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{11}
}

func (x *TransferCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *TransferCallRequest) GetPhoneNumber() *v0.PhoneNumber {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *TransferCallRequest) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type TransferCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Sdp    string `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Ufrag  string `protobuf:"bytes,3,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
}

func (x *TransferCallResponse) Reset() {
	*x = TransferCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCallResponse) ProtoMessage() {}

func (x *TransferCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCallResponse.ProtoReflect.Descriptor instead.
func (*TransferCallResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{12}
}

func (x *TransferCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *TransferCallResponse) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *TransferCallResponse) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

type SendIceCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId       string        `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	IceCandidate *IceCandidate `protobuf:"bytes,2,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"`
}

func (x *SendIceCandidateRequest) Reset() {
	*x = SendIceCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendIceCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendIceCandidateRequest) ProtoMessage() {}

func (x *SendIceCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendIceCandidateRequest.ProtoReflect.Descriptor instead.
func (*SendIceCandidateRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{13}
}

func (x *SendIceCandidateRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SendIceCandidateRequest) GetIceCandidate() *IceCandidate {
	if x != nil {
		return x.IceCandidate
	}
	return nil
}

type SendIceCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendIceCandidateResponse) Reset() {
	*x = SendIceCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendIceCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendIceCandidateResponse) ProtoMessage() {}

func (x *SendIceCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendIceCandidateResponse.ProtoReflect.Descriptor instead.
func (*SendIceCandidateResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{14}
}

type GetIceCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Ufrag  string `protobuf:"bytes,2,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
}

func (x *GetIceCandidateRequest) Reset() {
	*x = GetIceCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIceCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIceCandidateRequest) ProtoMessage() {}

func (x *GetIceCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIceCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetIceCandidateRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{15}
}

func (x *GetIceCandidateRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetIceCandidateRequest) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

type GetIceCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId       string        `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Ufrag        string        `protobuf:"bytes,2,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
	IceCandidate *IceCandidate `protobuf:"bytes,3,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"`
}

func (x *GetIceCandidateResponse) Reset() {
	*x = GetIceCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIceCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIceCandidateResponse) ProtoMessage() {}

func (x *GetIceCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIceCandidateResponse.ProtoReflect.Descriptor instead.
func (*GetIceCandidateResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{16}
}

func (x *GetIceCandidateResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetIceCandidateResponse) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

func (x *GetIceCandidateResponse) GetIceCandidate() *IceCandidate {
	if x != nil {
		return x.IceCandidate
	}
	return nil
}

type IceCandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate  string `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	MlineIndex int32  `protobuf:"varint,2,opt,name=mline_index,json=mlineIndex,proto3" json:"mline_index,omitempty"`
	Mid        string `protobuf:"bytes,3,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{17}
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *IceCandidate) GetMlineIndex() int32 {
	if x != nil {
		return x.MlineIndex
	}
	return 0
}

func (x *IceCandidate) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type HangupCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId      string          `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	PhoneNumber *v0.PhoneNumber `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *HangupCallRequest) Reset() {
	*x = HangupCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HangupCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallRequest) ProtoMessage() {}

func (x *HangupCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallRequest.ProtoReflect.Descriptor instead.
func (*HangupCallRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{18}
}

func (x *HangupCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *HangupCallRequest) GetPhoneNumber() *v0.PhoneNumber {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

type HangupCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HangupCallResponse) Reset() {
	*x = HangupCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HangupCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallResponse) ProtoMessage() {}

func (x *HangupCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallResponse.ProtoReflect.Descriptor instead.
func (*HangupCallResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{19}
}

type SendDtmfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId string               `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Dtmf   SendDtmfRequest_Dtmf `protobuf:"varint,2,opt,name=dtmf,proto3,enum=wgtwo.calling.v0.SendDtmfRequest_Dtmf" json:"dtmf,omitempty"`
}

func (x *SendDtmfRequest) Reset() {
	*x = SendDtmfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDtmfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDtmfRequest) ProtoMessage() {}

func (x *SendDtmfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDtmfRequest.ProtoReflect.Descriptor instead.
func (*SendDtmfRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{20}
}

func (x *SendDtmfRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SendDtmfRequest) GetDtmf() SendDtmfRequest_Dtmf {
	if x != nil {
		return x.Dtmf
	}
	return SendDtmfRequest_ZERO
}

type SendDtmfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendDtmfResponse) Reset() {
	*x = SendDtmfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDtmfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDtmfResponse) ProtoMessage() {}

func (x *SendDtmfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_calling_v0_calling_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDtmfResponse.ProtoReflect.Descriptor instead.
func (*SendDtmfResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_calling_v0_calling_proto_rawDescGZIP(), []int{21}
}

var File_wgtwo_calling_v0_calling_proto protoreflect.FileDescriptor

var file_wgtwo_calling_v0_calling_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2f,
	0x76, 0x30, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x30, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x21, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76,
	0x30, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x67,
	0x74, 0x77, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x57, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x75, 0x72,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x0b, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x54, 0x75, 0x72, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x0a, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22,
	0x5a, 0x0a, 0x0a, 0x54, 0x75, 0x72, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0xd9, 0x01, 0x0a, 0x10,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x04, 0x69, 0x6e,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f,
	0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x42, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f,
	0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xb9, 0x01, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74,
	0x12, 0x3d, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x39, 0x0a, 0x09, 0x74, 0x6f, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x08, 0x74, 0x6f, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x03, 0x73, 0x64,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e,
	0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x64, 0x70, 0x52, 0x03,
	0x73, 0x64, 0x70, 0x22, 0x82, 0x01, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x3f,
	0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77,
	0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e,
	0x53, 0x64, 0x70, 0x52, 0x03, 0x73, 0x64, 0x70, 0x22, 0xfc, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0a, 0x6b, 0x65, 0x65, 0x70, 0x5f,
	0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x77, 0x67,
	0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x4b,
	0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6b, 0x65, 0x65, 0x70,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x64, 0x70, 0x48, 0x00, 0x52, 0x03, 0x73, 0x64, 0x70,
	0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x30, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x2c, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x30, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x45, 0x0a, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xb6,
	0x01, 0x0a, 0x03, 0x53, 0x64, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x66, 0x72, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x66, 0x72, 0x61, 0x67, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63,
	0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x64, 0x70, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x1d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x4f, 0x46, 0x46, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x01, 0x22, 0x4b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xc4, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76,
	0x30, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x49, 0x4e, 0x47, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x47, 0x4f, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x48, 0x41, 0x4e, 0x47, 0x55, 0x50, 0x5f, 0x42, 0x55, 0x53, 0x59, 0x10, 0x04, 0x12,
	0x0a, 0x0a, 0x06, 0x48, 0x41, 0x4e, 0x47, 0x55, 0x50, 0x10, 0x05, 0x22, 0x81, 0x01, 0x0a, 0x13,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0c,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x64, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x22,
	0x57, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x64, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x66, 0x72, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x75, 0x66, 0x72, 0x61, 0x67, 0x22, 0x77, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64,
	0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0d,
	0x69, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x0c, 0x69, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x75, 0x66, 0x72, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x75, 0x66, 0x72, 0x61, 0x67, 0x22, 0x8d, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x49, 0x63,
	0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x75,
	0x66, 0x72, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x66, 0x72, 0x61,
	0x67, 0x12, 0x43, 0x0a, 0x0d, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f,
	0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x63, 0x65, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x69, 0x63, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0x5f, 0x0a, 0x0c, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x6c, 0x69, 0x6e, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x22, 0x6d, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x67, 0x75,
	0x70, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x67,
	0x74, 0x77, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x48, 0x61, 0x6e, 0x67, 0x75, 0x70,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xe6, 0x01, 0x0a,
	0x0f, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x74, 0x6d, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x74, 0x6d,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e,
	0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44,
	0x74, 0x6d, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x74, 0x6d, 0x66, 0x52,
	0x04, 0x64, 0x74, 0x6d, 0x66, 0x22, 0x7e, 0x0a, 0x04, 0x44, 0x74, 0x6d, 0x66, 0x12, 0x08, 0x0a,
	0x04, 0x5a, 0x45, 0x52, 0x4f, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x4e, 0x45, 0x10, 0x01,
	0x12, 0x07, 0x0a, 0x03, 0x54, 0x57, 0x4f, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x48, 0x52,
	0x45, 0x45, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4f, 0x55, 0x52, 0x10, 0x04, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x49, 0x56, 0x45, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x49, 0x58, 0x10,
	0x06, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x45, 0x56, 0x45, 0x4e, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x49, 0x47, 0x48, 0x54, 0x10, 0x08, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x49, 0x4e, 0x45, 0x10,
	0x09, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x41, 0x52, 0x10, 0x0a, 0x12, 0x08, 0x0a, 0x04, 0x48,
	0x41, 0x53, 0x48, 0x10, 0x0b, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x74, 0x6d,
	0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbc, 0x05, 0x0a, 0x0e, 0x43, 0x61,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x22, 0x2e, 0x77, 0x67, 0x74, 0x77,
	0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x5f, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x25, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f,
	0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x30, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x08, 0x53, 0x65, 0x6e,
	0x64, 0x44, 0x74, 0x6d, 0x66, 0x12, 0x21, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x74, 0x6d,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f,
	0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x44, 0x74, 0x6d, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x0a, 0x48, 0x61, 0x6e, 0x67, 0x75, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x23, 0x2e, 0x77,
	0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e,
	0x48, 0x61, 0x6e, 0x67, 0x75, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x30, 0x2e, 0x48, 0x61, 0x6e, 0x67, 0x75, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x54, 0x75, 0x72, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x27, 0x2e, 0x77, 0x67,
	0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x6a, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x29, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x63, 0x65, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76,
	0x30, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x28, 0x2e, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x77, 0x67, 0x74, 0x77,
	0x6f, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x61, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e,
	0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x30, 0x42, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77,
	0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x74, 0x77, 0x6f,
	0x2f, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x77, 0x67, 0x74, 0x77, 0x6f,
	0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_wgtwo_calling_v0_calling_proto_rawDescOnce sync.Once
	file_wgtwo_calling_v0_calling_proto_rawDescData = file_wgtwo_calling_v0_calling_proto_rawDesc
)

func file_wgtwo_calling_v0_calling_proto_rawDescGZIP() []byte {
	file_wgtwo_calling_v0_calling_proto_rawDescOnce.Do(func() {
		file_wgtwo_calling_v0_calling_proto_rawDescData = protoimpl.X.CompressGZIP(file_wgtwo_calling_v0_calling_proto_rawDescData)
	})
	return file_wgtwo_calling_v0_calling_proto_rawDescData
}

var file_wgtwo_calling_v0_calling_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wgtwo_calling_v0_calling_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_wgtwo_calling_v0_calling_proto_goTypes = []interface{}{
	(Sdp_Type)(0),                    // 0: wgtwo.calling.v0.Sdp.Type
	(Info_Message)(0),                // 1: wgtwo.calling.v0.Info.Message
	(SendDtmfRequest_Dtmf)(0),        // 2: wgtwo.calling.v0.SendDtmfRequest.Dtmf
	(*GetTurnServersRequest)(nil),    // 3: wgtwo.calling.v0.GetTurnServersRequest
	(*GetTurnServersResponse)(nil),   // 4: wgtwo.calling.v0.GetTurnServersResponse
	(*TurnServer)(nil),               // 5: wgtwo.calling.v0.TurnServer
	(*StartCallRequest)(nil),         // 6: wgtwo.calling.v0.StartCallRequest
	(*StartCallRequestInit)(nil),     // 7: wgtwo.calling.v0.StartCallRequestInit
	(*StartCallRequestUpdate)(nil),   // 8: wgtwo.calling.v0.StartCallRequestUpdate
	(*StartCallResponse)(nil),        // 9: wgtwo.calling.v0.StartCallResponse
	(*KeepAlive)(nil),                // 10: wgtwo.calling.v0.KeepAlive
	(*Sdp)(nil),                      // 11: wgtwo.calling.v0.Sdp
	(*Error)(nil),                    // 12: wgtwo.calling.v0.Error
	(*Info)(nil),                     // 13: wgtwo.calling.v0.Info
	(*TransferCallRequest)(nil),      // 14: wgtwo.calling.v0.TransferCallRequest
	(*TransferCallResponse)(nil),     // 15: wgtwo.calling.v0.TransferCallResponse
	(*SendIceCandidateRequest)(nil),  // 16: wgtwo.calling.v0.SendIceCandidateRequest
	(*SendIceCandidateResponse)(nil), // 17: wgtwo.calling.v0.SendIceCandidateResponse
	(*GetIceCandidateRequest)(nil),   // 18: wgtwo.calling.v0.GetIceCandidateRequest
	(*GetIceCandidateResponse)(nil),  // 19: wgtwo.calling.v0.GetIceCandidateResponse
	(*IceCandidate)(nil),             // 20: wgtwo.calling.v0.IceCandidate
	(*HangupCallRequest)(nil),        // 21: wgtwo.calling.v0.HangupCallRequest
	(*HangupCallResponse)(nil),       // 22: wgtwo.calling.v0.HangupCallResponse
	(*SendDtmfRequest)(nil),          // 23: wgtwo.calling.v0.SendDtmfRequest
	(*SendDtmfResponse)(nil),         // 24: wgtwo.calling.v0.SendDtmfResponse
	(*v0.PhoneNumber)(nil),           // 25: wgtwo.common.v0.PhoneNumber
	(*timestamp.Timestamp)(nil),      // 26: google.protobuf.Timestamp
}
var file_wgtwo_calling_v0_calling_proto_depIdxs = []int32{
	25, // 0: wgtwo.calling.v0.GetTurnServersRequest.phone_number:type_name -> wgtwo.common.v0.PhoneNumber
	5,  // 1: wgtwo.calling.v0.GetTurnServersResponse.turn_server:type_name -> wgtwo.calling.v0.TurnServer
	7,  // 2: wgtwo.calling.v0.StartCallRequest.init:type_name -> wgtwo.calling.v0.StartCallRequestInit
	8,  // 3: wgtwo.calling.v0.StartCallRequest.update:type_name -> wgtwo.calling.v0.StartCallRequestUpdate
	25, // 4: wgtwo.calling.v0.StartCallRequestInit.from_number:type_name -> wgtwo.common.v0.PhoneNumber
	25, // 5: wgtwo.calling.v0.StartCallRequestInit.to_number:type_name -> wgtwo.common.v0.PhoneNumber
	11, // 6: wgtwo.calling.v0.StartCallRequestInit.sdp:type_name -> wgtwo.calling.v0.Sdp
	25, // 7: wgtwo.calling.v0.StartCallRequestUpdate.phone_number:type_name -> wgtwo.common.v0.PhoneNumber
	11, // 8: wgtwo.calling.v0.StartCallRequestUpdate.sdp:type_name -> wgtwo.calling.v0.Sdp
	10, // 9: wgtwo.calling.v0.StartCallResponse.keep_alive:type_name -> wgtwo.calling.v0.KeepAlive
	11, // 10: wgtwo.calling.v0.StartCallResponse.sdp:type_name -> wgtwo.calling.v0.Sdp
	12, // 11: wgtwo.calling.v0.StartCallResponse.error:type_name -> wgtwo.calling.v0.Error
	13, // 12: wgtwo.calling.v0.StartCallResponse.info:type_name -> wgtwo.calling.v0.Info
	26, // 13: wgtwo.calling.v0.KeepAlive.timestamp:type_name -> google.protobuf.Timestamp
	26, // 14: wgtwo.calling.v0.Sdp.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 15: wgtwo.calling.v0.Sdp.type:type_name -> wgtwo.calling.v0.Sdp.Type
	1,  // 16: wgtwo.calling.v0.Info.message:type_name -> wgtwo.calling.v0.Info.Message
	25, // 17: wgtwo.calling.v0.TransferCallRequest.phone_number:type_name -> wgtwo.common.v0.PhoneNumber
	20, // 18: wgtwo.calling.v0.SendIceCandidateRequest.ice_candidate:type_name -> wgtwo.calling.v0.IceCandidate
	20, // 19: wgtwo.calling.v0.GetIceCandidateResponse.ice_candidate:type_name -> wgtwo.calling.v0.IceCandidate
	25, // 20: wgtwo.calling.v0.HangupCallRequest.phone_number:type_name -> wgtwo.common.v0.PhoneNumber
	2,  // 21: wgtwo.calling.v0.SendDtmfRequest.dtmf:type_name -> wgtwo.calling.v0.SendDtmfRequest.Dtmf
	6,  // 22: wgtwo.calling.v0.CallingService.StartCall:input_type -> wgtwo.calling.v0.StartCallRequest
	14, // 23: wgtwo.calling.v0.CallingService.TransferCall:input_type -> wgtwo.calling.v0.TransferCallRequest
	23, // 24: wgtwo.calling.v0.CallingService.SendDtmf:input_type -> wgtwo.calling.v0.SendDtmfRequest
	21, // 25: wgtwo.calling.v0.CallingService.HangupCall:input_type -> wgtwo.calling.v0.HangupCallRequest
	3,  // 26: wgtwo.calling.v0.CallingService.GetTurnServers:input_type -> wgtwo.calling.v0.GetTurnServersRequest
	16, // 27: wgtwo.calling.v0.CallingService.SetIceCandidate:input_type -> wgtwo.calling.v0.SendIceCandidateRequest
	18, // 28: wgtwo.calling.v0.CallingService.GetIceCandidate:input_type -> wgtwo.calling.v0.GetIceCandidateRequest
	9,  // 29: wgtwo.calling.v0.CallingService.StartCall:output_type -> wgtwo.calling.v0.StartCallResponse
	15, // 30: wgtwo.calling.v0.CallingService.TransferCall:output_type -> wgtwo.calling.v0.TransferCallResponse
	24, // 31: wgtwo.calling.v0.CallingService.SendDtmf:output_type -> wgtwo.calling.v0.SendDtmfResponse
	22, // 32: wgtwo.calling.v0.CallingService.HangupCall:output_type -> wgtwo.calling.v0.HangupCallResponse
	4,  // 33: wgtwo.calling.v0.CallingService.GetTurnServers:output_type -> wgtwo.calling.v0.GetTurnServersResponse
	17, // 34: wgtwo.calling.v0.CallingService.SetIceCandidate:output_type -> wgtwo.calling.v0.SendIceCandidateResponse
	19, // 35: wgtwo.calling.v0.CallingService.GetIceCandidate:output_type -> wgtwo.calling.v0.GetIceCandidateResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_wgtwo_calling_v0_calling_proto_init() }
func file_wgtwo_calling_v0_calling_proto_init() {
	if File_wgtwo_calling_v0_calling_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wgtwo_calling_v0_calling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTurnServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTurnServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TurnServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCallRequestInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCallRequestUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sdp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendIceCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendIceCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIceCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIceCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IceCandidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HangupCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HangupCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDtmfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_calling_v0_calling_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDtmfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_wgtwo_calling_v0_calling_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*StartCallRequest_Init)(nil),
		(*StartCallRequest_Update)(nil),
	}
	file_wgtwo_calling_v0_calling_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*StartCallResponse_KeepAlive)(nil),
		(*StartCallResponse_Sdp)(nil),
		(*StartCallResponse_Error)(nil),
		(*StartCallResponse_Info)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wgtwo_calling_v0_calling_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wgtwo_calling_v0_calling_proto_goTypes,
		DependencyIndexes: file_wgtwo_calling_v0_calling_proto_depIdxs,
		EnumInfos:         file_wgtwo_calling_v0_calling_proto_enumTypes,
		MessageInfos:      file_wgtwo_calling_v0_calling_proto_msgTypes,
	}.Build()
	File_wgtwo_calling_v0_calling_proto = out.File
	file_wgtwo_calling_v0_calling_proto_rawDesc = nil
	file_wgtwo_calling_v0_calling_proto_goTypes = nil
	file_wgtwo_calling_v0_calling_proto_depIdxs = nil
}
