// Copyright 2020 [Working Group Two]/[Cisco Systems]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: wgtwo/common/v0/phonenumber.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A phone number that is tied to a specific country.
type PhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Phone number formatted as E.164 with leading plus sign.<p/>
	// This contains of three components: <p/>
	// - The plus prefix <br>
	// - Country code, max 3 digits <br>
	// - Subscriber number <p/>
	// Test your number at <https://libphonenumber.appspot.com/> <p/>
	// Example: +12024561111
	E164 string `protobuf:"bytes,1,opt,name=e164,proto3" json:"e164,omitempty"`
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_common_v0_phonenumber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_common_v0_phonenumber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_wgtwo_common_v0_phonenumber_proto_rawDescGZIP(), []int{0}
}

func (x *PhoneNumber) GetE164() string {
	if x != nil {
		return x.E164
	}
	return ""
}

// An address that is non-numerical, e.g. "MyProduct".
type TextAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The value as a string.
	TextAddress string `protobuf:"bytes,1,opt,name=text_address,json=textAddress,proto3" json:"text_address,omitempty"`
}

func (x *TextAddress) Reset() {
	*x = TextAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_common_v0_phonenumber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAddress) ProtoMessage() {}

func (x *TextAddress) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_common_v0_phonenumber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAddress.ProtoReflect.Descriptor instead.
func (*TextAddress) Descriptor() ([]byte, []int) {
	return file_wgtwo_common_v0_phonenumber_proto_rawDescGZIP(), []int{1}
}

func (x *TextAddress) GetTextAddress() string {
	if x != nil {
		return x.TextAddress
	}
	return ""
}

// Any phone number that is tied to a specific country.
// Does not contain the prefix '+' nor a country code.
type NationalPhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The value as a string.
	NationalPhoneNumber string `protobuf:"bytes,1,opt,name=national_phone_number,json=nationalPhoneNumber,proto3" json:"national_phone_number,omitempty"`
}

func (x *NationalPhoneNumber) Reset() {
	*x = NationalPhoneNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wgtwo_common_v0_phonenumber_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NationalPhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NationalPhoneNumber) ProtoMessage() {}

func (x *NationalPhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_common_v0_phonenumber_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NationalPhoneNumber.ProtoReflect.Descriptor instead.
func (*NationalPhoneNumber) Descriptor() ([]byte, []int) {
	return file_wgtwo_common_v0_phonenumber_proto_rawDescGZIP(), []int{2}
}

func (x *NationalPhoneNumber) GetNationalPhoneNumber() string {
	if x != nil {
		return x.NationalPhoneNumber
	}
	return ""
}

var File_wgtwo_common_v0_phonenumber_proto protoreflect.FileDescriptor

var file_wgtwo_common_v0_phonenumber_proto_rawDesc = []byte{
	0x0a, 0x21, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76,
	0x30, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x31, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x65, 0x31, 0x36, 0x34, 0x22, 0x30, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65,
	0x78, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x49, 0x0a, 0x13, 0x4e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x32, 0x0a, 0x15, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x42, 0xbd, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x67, 0x74,
	0x77, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x42, 0x10, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x74, 0x77, 0x6f, 0x2f, 0x77,
	0x67, 0x74, 0x77, 0x6f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x77, 0x67, 0x74, 0x77, 0x6f, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x30, 0xa2, 0x02, 0x03, 0x57, 0x43, 0x56, 0xaa, 0x02,
	0x0f, 0x57, 0x67, 0x74, 0x77, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x30,
	0xca, 0x02, 0x0f, 0x57, 0x67, 0x74, 0x77, 0x6f, 0x5c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c,
	0x56, 0x30, 0xe2, 0x02, 0x1b, 0x57, 0x67, 0x74, 0x77, 0x6f, 0x5c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5c, 0x56, 0x30, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x11, 0x57, 0x67, 0x74, 0x77, 0x6f, 0x3a, 0x3a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x3a, 0x3a, 0x56, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wgtwo_common_v0_phonenumber_proto_rawDescOnce sync.Once
	file_wgtwo_common_v0_phonenumber_proto_rawDescData = file_wgtwo_common_v0_phonenumber_proto_rawDesc
)

func file_wgtwo_common_v0_phonenumber_proto_rawDescGZIP() []byte {
	file_wgtwo_common_v0_phonenumber_proto_rawDescOnce.Do(func() {
		file_wgtwo_common_v0_phonenumber_proto_rawDescData = protoimpl.X.CompressGZIP(file_wgtwo_common_v0_phonenumber_proto_rawDescData)
	})
	return file_wgtwo_common_v0_phonenumber_proto_rawDescData
}

var file_wgtwo_common_v0_phonenumber_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wgtwo_common_v0_phonenumber_proto_goTypes = []any{
	(*PhoneNumber)(nil),         // 0: wgtwo.common.v0.PhoneNumber
	(*TextAddress)(nil),         // 1: wgtwo.common.v0.TextAddress
	(*NationalPhoneNumber)(nil), // 2: wgtwo.common.v0.NationalPhoneNumber
}
var file_wgtwo_common_v0_phonenumber_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wgtwo_common_v0_phonenumber_proto_init() }
func file_wgtwo_common_v0_phonenumber_proto_init() {
	if File_wgtwo_common_v0_phonenumber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wgtwo_common_v0_phonenumber_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PhoneNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_common_v0_phonenumber_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TextAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wgtwo_common_v0_phonenumber_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NationalPhoneNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wgtwo_common_v0_phonenumber_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wgtwo_common_v0_phonenumber_proto_goTypes,
		DependencyIndexes: file_wgtwo_common_v0_phonenumber_proto_depIdxs,
		MessageInfos:      file_wgtwo_common_v0_phonenumber_proto_msgTypes,
	}.Build()
	File_wgtwo_common_v0_phonenumber_proto = out.File
	file_wgtwo_common_v0_phonenumber_proto_rawDesc = nil
	file_wgtwo_common_v0_phonenumber_proto_goTypes = nil
	file_wgtwo_common_v0_phonenumber_proto_depIdxs = nil
}
