// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: wgtwo/annotations/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum representing the release status of API methods.
//
// More guidance around release status can be found in the
// [API Lifecycle documentation](https://developer.cisco.com/docs/mobility-services/api-lifecycle/).
type ReleaseStatus int32

const (
	// Default status when unspecified.
	ReleaseStatus_UNSPECIFIED ReleaseStatus = 0
	// Indicates a stable method, suitable for production use.
	// No breaking changes will be made to this method.
	ReleaseStatus_STABLE ReleaseStatus = 1
	// Indicates a beta method, suitable for initial development and testing.
	// Note that breaking changes may occur without notice.
	//
	// Most new methods will be released as beta, awaiting feedback from developers.
	ReleaseStatus_BETA ReleaseStatus = 2
	// Indicates a deprecated method.
	// It is recommended to migrate to newer alternatives if available.
	//
	// Please consult the
	// [Cisco DevNet Mobility Services API documentation](https://docs.mobility.cisco.com/)
	// for guidance.
	ReleaseStatus_DEPRECATED ReleaseStatus = 3
)

// Enum value maps for ReleaseStatus.
var (
	ReleaseStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "STABLE",
		2: "BETA",
		3: "DEPRECATED",
	}
	ReleaseStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"STABLE":      1,
		"BETA":        2,
		"DEPRECATED":  3,
	}
)

func (x ReleaseStatus) Enum() *ReleaseStatus {
	p := new(ReleaseStatus)
	*p = x
	return p
}

func (x ReleaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReleaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wgtwo_annotations_annotations_proto_enumTypes[0].Descriptor()
}

func (ReleaseStatus) Type() protoreflect.EnumType {
	return &file_wgtwo_annotations_annotations_proto_enumTypes[0]
}

func (x ReleaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReleaseStatus.Descriptor instead.
func (ReleaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_wgtwo_annotations_annotations_proto_rawDescGZIP(), []int{0}
}

var file_wgtwo_annotations_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50013,
		Name:          "wgtwo.scope",
		Tag:           "bytes,50013,opt,name=scope",
		Filename:      "wgtwo/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ReleaseStatus)(nil),
		Field:         50015,
		Name:          "wgtwo.status",
		Tag:           "varint,50015,opt,name=status,enum=wgtwo.ReleaseStatus",
		Filename:      "wgtwo/annotations/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Specifies the required access scope for this method.
	//
	// optional string scope = 50013;
	E_Scope = &file_wgtwo_annotations_annotations_proto_extTypes[0]
	// The release status of the method.
	//
	// optional wgtwo.ReleaseStatus status = 50015;
	E_Status = &file_wgtwo_annotations_annotations_proto_extTypes[1]
)

var File_wgtwo_annotations_annotations_proto protoreflect.FileDescriptor

const file_wgtwo_annotations_annotations_proto_rawDesc = "" +
	"\n" +
	"#wgtwo/annotations/annotations.proto\x12\x05wgtwo\x1a google/protobuf/descriptor.proto*F\n" +
	"\rReleaseStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STABLE\x10\x01\x12\b\n" +
	"\x04BETA\x10\x02\x12\x0e\n" +
	"\n" +
	"DEPRECATED\x10\x03:6\n" +
	"\x05scope\x12\x1e.google.protobuf.MethodOptions\x18݆\x03 \x01(\tR\x05scope:N\n" +
	"\x06status\x12\x1e.google.protobuf.MethodOptions\x18߆\x03 \x01(\x0e2\x14.wgtwo.ReleaseStatusR\x06statusB\x8b\x01\n" +
	"\tcom.wgtwoB\x10AnnotationsProtoP\x01Z8github.com/working-group-two/wgtwoapis/wgtwo/annotations\xa2\x02\x03WXX\xaa\x02\x05Wgtwo\xca\x02\x05Wgtwo\xe2\x02\x11Wgtwo\\GPBMetadata\xea\x02\x05Wgtwob\x06proto3"

var (
	file_wgtwo_annotations_annotations_proto_rawDescOnce sync.Once
	file_wgtwo_annotations_annotations_proto_rawDescData []byte
)

func file_wgtwo_annotations_annotations_proto_rawDescGZIP() []byte {
	file_wgtwo_annotations_annotations_proto_rawDescOnce.Do(func() {
		file_wgtwo_annotations_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wgtwo_annotations_annotations_proto_rawDesc), len(file_wgtwo_annotations_annotations_proto_rawDesc)))
	})
	return file_wgtwo_annotations_annotations_proto_rawDescData
}

var file_wgtwo_annotations_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wgtwo_annotations_annotations_proto_goTypes = []any{
	(ReleaseStatus)(0),                 // 0: wgtwo.ReleaseStatus
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_wgtwo_annotations_annotations_proto_depIdxs = []int32{
	1, // 0: wgtwo.scope:extendee -> google.protobuf.MethodOptions
	1, // 1: wgtwo.status:extendee -> google.protobuf.MethodOptions
	0, // 2: wgtwo.status:type_name -> wgtwo.ReleaseStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wgtwo_annotations_annotations_proto_init() }
func file_wgtwo_annotations_annotations_proto_init() {
	if File_wgtwo_annotations_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wgtwo_annotations_annotations_proto_rawDesc), len(file_wgtwo_annotations_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_wgtwo_annotations_annotations_proto_goTypes,
		DependencyIndexes: file_wgtwo_annotations_annotations_proto_depIdxs,
		EnumInfos:         file_wgtwo_annotations_annotations_proto_enumTypes,
		ExtensionInfos:    file_wgtwo_annotations_annotations_proto_extTypes,
	}.Build()
	File_wgtwo_annotations_annotations_proto = out.File
	file_wgtwo_annotations_annotations_proto_goTypes = nil
	file_wgtwo_annotations_annotations_proto_depIdxs = nil
}
