// Copyright 2023 [Working Group Two]/[Cisco Systems]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: wgtwo/products/v0/products.proto

package v0

import (
	_ "github.com/working-group-two/wgtwoapis/wgtwo/annotations"
	v0 "github.com/working-group-two/wgtwoapis/wgtwo/images/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductsForTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Show products available for tenant
	Tenant        string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsForTenantRequest) Reset() {
	*x = ListProductsForTenantRequest{}
	mi := &file_wgtwo_products_v0_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsForTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsForTenantRequest) ProtoMessage() {}

func (x *ListProductsForTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_products_v0_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsForTenantRequest.ProtoReflect.Descriptor instead.
func (*ListProductsForTenantRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_products_v0_products_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductsForTenantRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListProductsForTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsForTenantResponse) Reset() {
	*x = ListProductsForTenantResponse{}
	mi := &file_wgtwo_products_v0_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsForTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsForTenantResponse) ProtoMessage() {}

func (x *ListProductsForTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_products_v0_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsForTenantResponse.ProtoReflect.Descriptor instead.
func (*ListProductsForTenantResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_products_v0_products_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsForTenantResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle      string                 `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	ProductUrl    string                 `protobuf:"bytes,4,opt,name=product_url,json=productUrl,proto3" json:"product_url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Icon          *v0.Image              `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Banner        *v0.Image              `protobuf:"bytes,7,opt,name=banner,proto3" json:"banner,omitempty"`
	Images        []*v0.Image            `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_wgtwo_products_v0_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_products_v0_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_wgtwo_products_v0_products_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Product) GetProductUrl() string {
	if x != nil {
		return x.ProductUrl
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetIcon() *v0.Image {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *Product) GetBanner() *v0.Image {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *Product) GetImages() []*v0.Image {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_wgtwo_products_v0_products_proto protoreflect.FileDescriptor

const file_wgtwo_products_v0_products_proto_rawDesc = "" +
	"\n" +
	" wgtwo/products/v0/products.proto\x12\x11wgtwo.products.v0\x1a#wgtwo/annotations/annotations.proto\x1a\x1cwgtwo/images/v0/images.proto\"6\n" +
	"\x1cListProductsForTenantRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"W\n" +
	"\x1dListProductsForTenantResponse\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.wgtwo.products.v0.ProductR\bproducts\"\x98\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\x12\x1f\n" +
	"\vproduct_url\x18\x04 \x01(\tR\n" +
	"productUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12*\n" +
	"\x04icon\x18\x06 \x01(\v2\x16.wgtwo.images.v0.ImageR\x04icon\x12.\n" +
	"\x06banner\x18\a \x01(\v2\x16.wgtwo.images.v0.ImageR\x06banner\x12.\n" +
	"\x06images\x18\b \x03(\v2\x16.wgtwo.images.v0.ImageR\x06images2\xa7\x01\n" +
	"\x0eProductService\x12\x94\x01\n" +
	"\x15ListProductsForTenant\x12/.wgtwo.products.v0.ListProductsForTenantRequest\x1a0.wgtwo.products.v0.ListProductsForTenantResponse\"\x18\xea\xb5\x18\x14products.tenant:readB\xc6\x01\n" +
	"\x15com.wgtwo.products.v0B\rProductsProtoP\x01Z8github.com/working-group-two/wgtwoapis/wgtwo/products/v0\xa2\x02\x03WPV\xaa\x02\x11Wgtwo.Products.V0\xca\x02\x11Wgtwo\\Products\\V0\xe2\x02\x1dWgtwo\\Products\\V0\\GPBMetadata\xea\x02\x13Wgtwo::Products::V0b\x06proto3"

var (
	file_wgtwo_products_v0_products_proto_rawDescOnce sync.Once
	file_wgtwo_products_v0_products_proto_rawDescData []byte
)

func file_wgtwo_products_v0_products_proto_rawDescGZIP() []byte {
	file_wgtwo_products_v0_products_proto_rawDescOnce.Do(func() {
		file_wgtwo_products_v0_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wgtwo_products_v0_products_proto_rawDesc), len(file_wgtwo_products_v0_products_proto_rawDesc)))
	})
	return file_wgtwo_products_v0_products_proto_rawDescData
}

var file_wgtwo_products_v0_products_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wgtwo_products_v0_products_proto_goTypes = []any{
	(*ListProductsForTenantRequest)(nil),  // 0: wgtwo.products.v0.ListProductsForTenantRequest
	(*ListProductsForTenantResponse)(nil), // 1: wgtwo.products.v0.ListProductsForTenantResponse
	(*Product)(nil),                       // 2: wgtwo.products.v0.Product
	(*v0.Image)(nil),                      // 3: wgtwo.images.v0.Image
}
var file_wgtwo_products_v0_products_proto_depIdxs = []int32{
	2, // 0: wgtwo.products.v0.ListProductsForTenantResponse.products:type_name -> wgtwo.products.v0.Product
	3, // 1: wgtwo.products.v0.Product.icon:type_name -> wgtwo.images.v0.Image
	3, // 2: wgtwo.products.v0.Product.banner:type_name -> wgtwo.images.v0.Image
	3, // 3: wgtwo.products.v0.Product.images:type_name -> wgtwo.images.v0.Image
	0, // 4: wgtwo.products.v0.ProductService.ListProductsForTenant:input_type -> wgtwo.products.v0.ListProductsForTenantRequest
	1, // 5: wgtwo.products.v0.ProductService.ListProductsForTenant:output_type -> wgtwo.products.v0.ListProductsForTenantResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wgtwo_products_v0_products_proto_init() }
func file_wgtwo_products_v0_products_proto_init() {
	if File_wgtwo_products_v0_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wgtwo_products_v0_products_proto_rawDesc), len(file_wgtwo_products_v0_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wgtwo_products_v0_products_proto_goTypes,
		DependencyIndexes: file_wgtwo_products_v0_products_proto_depIdxs,
		MessageInfos:      file_wgtwo_products_v0_products_proto_msgTypes,
	}.Build()
	File_wgtwo_products_v0_products_proto = out.File
	file_wgtwo_products_v0_products_proto_goTypes = nil
	file_wgtwo_products_v0_products_proto_depIdxs = nil
}
