// Copyright 2023 [Working Group Two]/[Cisco Systems]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: wgtwo/lookup/v0/number_lookup.proto

package v0

import (
	_ "github.com/working-group-two/wgtwoapis/wgtwo/annotations"
	v0 "github.com/working-group-two/wgtwoapis/wgtwo/common/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberLookupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An ID representing the request, used for routing purposes
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The number to lookup
	Number        *v0.PhoneNumber `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberLookupRequest) Reset() {
	*x = NumberLookupRequest{}
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberLookupRequest) ProtoMessage() {}

func (x *NumberLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberLookupRequest.ProtoReflect.Descriptor instead.
func (*NumberLookupRequest) Descriptor() ([]byte, []int) {
	return file_wgtwo_lookup_v0_number_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *NumberLookupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NumberLookupRequest) GetNumber() *v0.PhoneNumber {
	if x != nil {
		return x.Number
	}
	return nil
}

type NumberLookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The origin request this response is for
	NumberLookupRequest *NumberLookupRequest `protobuf:"bytes,1,opt,name=number_lookup_request,json=numberLookupRequest,proto3" json:"number_lookup_request,omitempty"`
	// The result of the lookup
	// If neither Result nor Error is set, an empty Result is assumed
	//
	// Types that are valid to be assigned to Reply:
	//
	//	*NumberLookupResponse_Result
	//	*NumberLookupResponse_Error
	Reply isNumberLookupResponse_Reply `protobuf_oneof:"reply"`
	// Cache settings for this response
	CacheControl  *CacheControl `protobuf:"bytes,4,opt,name=cache_control,json=cacheControl,proto3" json:"cache_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberLookupResponse) Reset() {
	*x = NumberLookupResponse{}
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberLookupResponse) ProtoMessage() {}

func (x *NumberLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberLookupResponse.ProtoReflect.Descriptor instead.
func (*NumberLookupResponse) Descriptor() ([]byte, []int) {
	return file_wgtwo_lookup_v0_number_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *NumberLookupResponse) GetNumberLookupRequest() *NumberLookupRequest {
	if x != nil {
		return x.NumberLookupRequest
	}
	return nil
}

func (x *NumberLookupResponse) GetReply() isNumberLookupResponse_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *NumberLookupResponse) GetResult() *Result {
	if x != nil {
		if x, ok := x.Reply.(*NumberLookupResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *NumberLookupResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Reply.(*NumberLookupResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *NumberLookupResponse) GetCacheControl() *CacheControl {
	if x != nil {
		return x.CacheControl
	}
	return nil
}

type isNumberLookupResponse_Reply interface {
	isNumberLookupResponse_Reply()
}

type NumberLookupResponse_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type NumberLookupResponse_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*NumberLookupResponse_Result) isNumberLookupResponse_Reply() {}

func (*NumberLookupResponse_Error) isNumberLookupResponse_Reply() {}

type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name associated with the number
	// May be empty if no name is found
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_wgtwo_lookup_v0_number_lookup_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human readable description describing the error
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_wgtwo_lookup_v0_number_lookup_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CacheControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum duration for which this response can be cached.
	//
	// If unset or set to zero, default duration of 24 hours will be used.
	// If set to value lower than the minimum duration of 15 minutes, the minimum duration will be used.
	//
	// Note: The minimum and default values might be subject to change without notice.
	MaxAge        *durationpb.Duration `protobuf:"bytes,1,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheControl) Reset() {
	*x = CacheControl{}
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheControl) ProtoMessage() {}

func (x *CacheControl) ProtoReflect() protoreflect.Message {
	mi := &file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheControl.ProtoReflect.Descriptor instead.
func (*CacheControl) Descriptor() ([]byte, []int) {
	return file_wgtwo_lookup_v0_number_lookup_proto_rawDescGZIP(), []int{4}
}

func (x *CacheControl) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

var File_wgtwo_lookup_v0_number_lookup_proto protoreflect.FileDescriptor

const file_wgtwo_lookup_v0_number_lookup_proto_rawDesc = "" +
	"\n" +
	"#wgtwo/lookup/v0/number_lookup.proto\x12\x0fwgtwo.lookup.v0\x1a\x1egoogle/protobuf/duration.proto\x1a#wgtwo/annotations/annotations.proto\x1a!wgtwo/common/v0/phonenumber.proto\"[\n" +
	"\x13NumberLookupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x06number\x18\x02 \x01(\v2\x1c.wgtwo.common.v0.PhoneNumberR\x06number\"\xa0\x02\n" +
	"\x14NumberLookupResponse\x12X\n" +
	"\x15number_lookup_request\x18\x01 \x01(\v2$.wgtwo.lookup.v0.NumberLookupRequestR\x13numberLookupRequest\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x17.wgtwo.lookup.v0.ResultH\x00R\x06result\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x16.wgtwo.lookup.v0.ErrorH\x00R\x05error\x12B\n" +
	"\rcache_control\x18\x04 \x01(\v2\x1d.wgtwo.lookup.v0.CacheControlR\fcacheControlB\a\n" +
	"\x05reply\"\x1c\n" +
	"\x06Result\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\fCacheControl\x122\n" +
	"\amax_age\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge2\x8e\x01\n" +
	"\x13NumberLookupService\x12w\n" +
	"\fNumberLookup\x12%.wgtwo.lookup.v0.NumberLookupResponse\x1a$.wgtwo.lookup.v0.NumberLookupRequest\"\x16\xea\xb5\x18\x12lookup.number:read(\x010\x01B\xbe\x01\n" +
	"\x13com.wgtwo.lookup.v0B\x11NumberLookupProtoP\x01Z6github.com/working-group-two/wgtwoapis/wgtwo/lookup/v0\xa2\x02\x03WLV\xaa\x02\x0fWgtwo.Lookup.V0\xca\x02\x0fWgtwo\\Lookup\\V0\xe2\x02\x1bWgtwo\\Lookup\\V0\\GPBMetadata\xea\x02\x11Wgtwo::Lookup::V0b\x06proto3"

var (
	file_wgtwo_lookup_v0_number_lookup_proto_rawDescOnce sync.Once
	file_wgtwo_lookup_v0_number_lookup_proto_rawDescData []byte
)

func file_wgtwo_lookup_v0_number_lookup_proto_rawDescGZIP() []byte {
	file_wgtwo_lookup_v0_number_lookup_proto_rawDescOnce.Do(func() {
		file_wgtwo_lookup_v0_number_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wgtwo_lookup_v0_number_lookup_proto_rawDesc), len(file_wgtwo_lookup_v0_number_lookup_proto_rawDesc)))
	})
	return file_wgtwo_lookup_v0_number_lookup_proto_rawDescData
}

var file_wgtwo_lookup_v0_number_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wgtwo_lookup_v0_number_lookup_proto_goTypes = []any{
	(*NumberLookupRequest)(nil),  // 0: wgtwo.lookup.v0.NumberLookupRequest
	(*NumberLookupResponse)(nil), // 1: wgtwo.lookup.v0.NumberLookupResponse
	(*Result)(nil),               // 2: wgtwo.lookup.v0.Result
	(*Error)(nil),                // 3: wgtwo.lookup.v0.Error
	(*CacheControl)(nil),         // 4: wgtwo.lookup.v0.CacheControl
	(*v0.PhoneNumber)(nil),       // 5: wgtwo.common.v0.PhoneNumber
	(*durationpb.Duration)(nil),  // 6: google.protobuf.Duration
}
var file_wgtwo_lookup_v0_number_lookup_proto_depIdxs = []int32{
	5, // 0: wgtwo.lookup.v0.NumberLookupRequest.number:type_name -> wgtwo.common.v0.PhoneNumber
	0, // 1: wgtwo.lookup.v0.NumberLookupResponse.number_lookup_request:type_name -> wgtwo.lookup.v0.NumberLookupRequest
	2, // 2: wgtwo.lookup.v0.NumberLookupResponse.result:type_name -> wgtwo.lookup.v0.Result
	3, // 3: wgtwo.lookup.v0.NumberLookupResponse.error:type_name -> wgtwo.lookup.v0.Error
	4, // 4: wgtwo.lookup.v0.NumberLookupResponse.cache_control:type_name -> wgtwo.lookup.v0.CacheControl
	6, // 5: wgtwo.lookup.v0.CacheControl.max_age:type_name -> google.protobuf.Duration
	1, // 6: wgtwo.lookup.v0.NumberLookupService.NumberLookup:input_type -> wgtwo.lookup.v0.NumberLookupResponse
	0, // 7: wgtwo.lookup.v0.NumberLookupService.NumberLookup:output_type -> wgtwo.lookup.v0.NumberLookupRequest
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_wgtwo_lookup_v0_number_lookup_proto_init() }
func file_wgtwo_lookup_v0_number_lookup_proto_init() {
	if File_wgtwo_lookup_v0_number_lookup_proto != nil {
		return
	}
	file_wgtwo_lookup_v0_number_lookup_proto_msgTypes[1].OneofWrappers = []any{
		(*NumberLookupResponse_Result)(nil),
		(*NumberLookupResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wgtwo_lookup_v0_number_lookup_proto_rawDesc), len(file_wgtwo_lookup_v0_number_lookup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wgtwo_lookup_v0_number_lookup_proto_goTypes,
		DependencyIndexes: file_wgtwo_lookup_v0_number_lookup_proto_depIdxs,
		MessageInfos:      file_wgtwo_lookup_v0_number_lookup_proto_msgTypes,
	}.Build()
	File_wgtwo_lookup_v0_number_lookup_proto = out.File
	file_wgtwo_lookup_v0_number_lookup_proto_goTypes = nil
	file_wgtwo_lookup_v0_number_lookup_proto_depIdxs = nil
}
